// fetching
export const WEATHER_START_FETCHING = 'WEATHER_START_FETCHING';
export const WEATHER_STOP_FETCHING = 'WEATHER_STOP_FETCHING';
export const WEATHER_FILL = 'WEATHER_FILL';
export const WEATHER_SET_FETCHING_ERROR = 'WEATHER_SET_FETCHING_ERROR';

// async
export const WEATHER_FETCH_ASYNC = 'WEATHER_FETCH_ASYNC';

// filtration
export const WEATHER_SET_MIN_TEMPERATURE = 'WEATHER_SET_MIN_TEMPERATURE';
export const WEATHER_SET_MAX_TEMPERATURE = 'WEATHER_SET_MAX_TEMPERATURE';
export const WEATHER_SET_TYPE_OF_WEATHER = 'WEATHER_SET_TYPE_OF_WEATHER';
export const WEATHER_SET_MINTEMPVALID_ERROR = 'WEATHER_SET_MINTEMPVALID_ERROR';
export const WEATHER_SET_MAXTEMPVALID_ERROR = 'WEATHER_SET_MAXTEMPVALID_ERROR';
export const WEATHER_SET_STATUS_OF_FILTER = 'WEATHER_SET_STATUS_OF_FILTER';
