export const types = Object.freeze({
  // Sync
  WEATHER_START_FETCHING: 'WEATHER_START_FETCHING',
  WEATHER_STOP_FETCHING: 'WEATHER_STOP_FETCHING',
  WEATHER_FILL: 'WEATHER_FILL',
  WEATHER_SET_FETCHING_ERROR: 'WEATHER_SET_FETCHING_ERROR',
  DISPLAY_THE_SELECT_DAY: 'DISPLAY_THE_SELECT_DAY',

  // async
  WEATHER_FETCH_ASYNC: 'WEATHER_FETCH_ASYNC',
});
